# Generated by Django 4.2.24 on 2025-09-20 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="Lesson cover shown in menus.",
                        null=True,
                        upload_to="lessons/covers/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("english_text", models.CharField(max_length=255)),
                ("translation", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional picture for recognition exercises.",
                        null=True,
                        upload_to="cards/images/",
                    ),
                ),
                (
                    "audio",
                    models.FileField(
                        blank=True,
                        help_text="Optional pre-recorded pronunciation audio.",
                        null=True,
                        upload_to="cards/audio/",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Controls the order of the card inside the lesson; lower numbers appear first.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="lessons.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="StudyProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile",
                    models.CharField(
                        help_text="Identifier for a child profile or device. Can be a username or generated token.",
                        max_length=255,
                    ),
                ),
                ("current_card_index", models.PositiveIntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="lessons.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Study progress",
                "unique_together": {("profile", "lesson")},
            },
        ),
    ]
